### ISSUE TITLE
Handle illformed csv dataset

### ISSUE THREAD

**Issue by lmilhade** [askomics/flaskomics#183]
I tried to integrate a csv file with an empty name for the first column : 

```
,fluid
id1,plasma
id2,liquide coelomique
id3,mucus
id4,fluide seminal
```

I can upload the file without any problem and when I click on Integrate I am redirected to `localhost/integration` but the page is blank and I don't have any error message.

This also happens when I try to integrate multiple files at the same time, including one illformed csv.

**Comment by mboudet** [comment]
React really doesn't like having an empty key in an array.
Two possible fixes : 
1) If one or more column has an empty column name, we raise an exception (like when there is an issue in the file).
2) We put placeholder values if there are empty values in the header.

Frankly, I'd rather have an exception for compatibility with the API...

@abretaud thoughts?

**Comment by abretaud** [comment]
I see no good way to generate a useful column name, so I guess raising an error is the best yep
