### ISSUE TITLE
Table ordering in results only works on strings

### ISSUE THREAD

**Issue by mboudet** [askomics/flaskomics#192]
(Since all data received from virtuoso is typed as string)

**Comment by mboudet** [comment]
So, virtuoso returns everything as a string (and I don't think I can change that).
Since the query can come from the sparql console, we have no way of knowing if a column is expected to be an integer either..

Two way of doing it : either on the backend or frontend.

Backend : We try to convert all columns to int, then float, then string
Frontend : We override the 'sort' function of the table to try to cast the values as a number and sort accordingly
Something like : 

```
custom_compare(a, b){
    let result;
    let num_a;
    let num_b;
    if (typeof b === 'string') {
        num_a = Number(a)
        num_b = Number(b)
        if (Number.isNaN(num_a) || Number.isNaN(num_b)){
            result = b.localeCompare(a);
        } else {
            result = num_a > num_b ? -1 : ((num_a < num_b) ? 1 : 0);
        }
    } else {
      result = a > b ? -1 : ((a < b) ? 1 : 0);
    }
    return result;
  }
```

Not sure about performance for either..

**Comment by mboudet** [comment]
@abretaud Thoughts?

**Comment by abretaud** [comment]
Can't we guess the expected column type by looking at what was asked in the askomics query? Like "Column xx corresponds to attribute yy of entity zz, and we know it's an integer"

**Comment by mboudet** [comment]
We could (for the ask part). Still need to know if its a float or integer.
The issue is that for the sparql console, we have no idea which column it is. We can just extract variable name.

**Comment by mboudet** [comment]
For the frontend, I can keep it light by skipping the check if the first two elements ordered are not number.
(Only casting two elements instead of all of them)
