### ISSUE TITLE
Relations error with duplicate relation names (ex: GFF import with 'Parent')

### ISSUE THREAD

**Issue by mboudet** [askomics/flaskomics#248]
*Initial description was not completely correct, see below*

There seems to be additional relations generated when integrating GFF files. (Parent and Included_in linking entities who should not be linked)

**Comment by mboudet** [comment]
After looking at the generated RDF file, the issue is a bit complicated: 

The information about the 'start' and 'end' of a relation is actually fragmented. For instance, for the 'Parent' relation between the 'Gene' and 'Transcript' entity, we have two triples of interest (in addition to those defining it as an AskomicRelation:

```ttl
# This set the startpoint for the Parent relationship
<http://askomics.org/data/Parent> <http://www.w3.org/2000/01/rdf-schema#domain> <http://askomics.org/data/five_prime_UTR>
# This is the endpoint
<http://askomics.org/data/Parent> <http://www.w3.org/2000/01/rdf-schema#range> <http://askomics.org/data/gene>
```   
It works fine when this relation (eg: <http://askomics.org/data/Parent>) is only used by one entity.

When several entities use the same relation however (like with GFF files, where multiple entities are linked with the Parent or Included_in relations), all the startpoints and all the endpoints are merged. Meaning, a relation will be created between any startpoint and any endpoint.

In the following image, the only 'real' relations are the one between transcript and gene, and all the other entities and transcript.
There should not be any relation between the other entities and gene, nor a transcript -> transcript relation.

![image](https://user-images.githubusercontent.com/17642511/129726419-614247a6-348d-43ee-ad69-cf16b3c75f3a.png)

**Comment by mboudet** [comment]
So, I'm not sure how to fix this without breaking the retro-compatibility.

- We could force the relation name to include the starting entity name (ie: TranscriptParent)? (anything goes as long as the (entity name, relation name) pair is unique to avoid mixup.
    - But this is not compatible with existing data: newly integrated data will show as a separate relation
    - Maybe writing a script to rewrite existing data would be possible, but it would break existing saved queries...

Maybe a config option 'compatibility_mode' ? If set to false, newly created relation will follow the entityname_relationname pattern for the URI.

**Comment by mboudet** [comment]
@ofilangi I would be interested in your perspective on this issue.

**Comment by ofilangi** [comment]
Due to the fact that the model is based on a triplet basis, the domain and range of a relation (askomics abstraction) should be targeted by an anonymous node.

```
: Parent: askomicsRelation [
  rdfs:range :gene 
  rdfs:domain :five_prime_UTR 
]
```
For a better management with "remote" relation maybe we should add origin 

```
: Parent: askomicsRelation [
  rdfs:range :gene 
  rdfs:domain :five_prime_UTR 
  :origin <endpoint1>
]
```

**Comment by mboudet** [comment]
@ofilangi 

So, we would keep the current relation definition (partially) : 
```ttl
<http://askomics.org/data/Parent> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#ObjectProperty> .
<http://askomics.org/data/Parent> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://askomics.org/internal/AskomicsRelation> .
<http://askomics.org/data/Parent> <http://www.w3.org/2000/01/rdf-schema#label> "Parent" .
# Removed range and domain
```
And add a blank node containing range and domain?
```ttl
<Blank> <predicate> <http://askomics.org/data/Parent> 
<Blank> <http://www.w3.org/2000/01/rdf-schema#domain> <http://askomics.org/data/transcript> .
<Blank> <http://www.w3.org/2000/01/rdf-schema#range> <http://askomics.org/data/gene> .

```
Something like this ? (Maybe I am mistaken on the predicate/object)

**Comment by ofilangi** [comment]
Yes, it's seems ok !
here a  example/proposal for a new definition :  
```turtle
_:DefParent  [
   a askomics:AskomicsRelation ;
   rdfs:label "Parent" ;
   rdfs:domain <http://askomics.org/data/transcript> ;
   rdfs:range <http://askomics.org/data/gene> ;
  dcat:endpointURL <url...>
] .
```
